// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbjjdyiorufngyfcxkyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiampkeWlvcnVmbmd5ZmN4a3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzIzMDAsImV4cCI6MjA2NDg0ODMwMH0.9Wtt8Xg7AilhMwWWEz_MAtXmLs5Uvd39g_QzNkWXd-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);